# Generated by Django 4.1.7 on 2023-03-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
